language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t borzak50/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true borzak50/docker-react npm run test
